
name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_glow : ^0.2.0
  http: ^0.13.5
  intl: ^0.17.0

  syncfusion_flutter_charts: ^19.4.47
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/




